server:
  port: 8080

chromadb:
  host: ${CHROMADB_HOST:http://localhost:8001}
  collection-name: documents

rag:
  service:
    base-url: ${RAG_SERVICE_BASE_URL:http://192.168.2.37:8082}

openai:
  api-key: ${OPENAI_API_KEY:}
  embedding-model: ${OPENAI_EMBEDDING_MODEL:text-embedding-3-small}
  embedding-url: https://api.openai.com/v1/embeddings
  chunk-size: ${OPENAI_CHUNK_SIZE:1000}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
